In [81]:
# importing dependancies
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [82]:
# loading csv file to a pandas df
credit_card = pd.read_csv('creditcard.csv')

In [83]:
credit_card.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [84]:
credit_card.shape

(284807, 31)

In [85]:
credit_card.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [86]:
# missing values
credit_card.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [87]:
# distribution of legit transaction and fraud transactions
credit_card['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This dataset is highly unbalanced

0 ---> normal transaction
1 ---> fraud transaction

In [88]:
# separating the data for analysis
legit = credit_card[credit_card.Class == 0]
fraud = credit_card[credit_card.Class == 1]

In [89]:
print(legit.shape)

(284315, 31)

In [90]:
print(fraud.shape)

(492, 31)

In [91]:
# statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [92]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [93]:
# compare the values for both transactions
credit_card.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

### Under-Sampling
Building a sample dataset containing similar distribution of normal transactions and fradulent transactions
fraud ---> 492
legit ---> 2841315

In [94]:
legit_sample = legit.sample(n=492)

### concateneting two dataframes

In [95]:
# concateneting two dataframes
new_df = pd.concat([legit_sample, fraud], axis=0)

In [96]:
new_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
37059,38790.0,-0.327923,0.209546,1.200571,-1.127178,-0.099165,-0.284337,0.523055,0.068633,0.108356,...,0.125672,0.227305,0.124639,-0.233042,-0.470058,0.851426,-0.042892,0.028083,72.44,0
116424,74270.0,-1.142794,1.641385,0.865726,0.309667,-0.812529,-0.852074,-0.884873,-2.243079,-0.787290,...,-1.408377,-0.281292,0.340870,0.814892,-0.381256,0.011395,-0.161385,0.005226,1.98,0
62335,50233.0,1.135303,-0.024541,0.209504,0.479848,-0.298684,-0.685790,0.186939,-0.226366,0.012765,...,-0.237147,-0.855756,-0.001254,-0.096710,0.245629,0.220479,-0.050839,0.028222,87.28,0
252637,155900.0,-0.531704,0.680875,0.597119,-1.028759,0.827708,-1.201487,1.171974,-0.241301,-0.185141,...,0.356074,0.982666,-0.369173,-0.060918,0.293462,-0.204899,0.091335,0.136623,19.95,0
180064,124360.0,-0.693474,0.643828,0.326878,-0.905386,1.281424,-0.016567,1.581390,-0.503492,-0.189510,...,-0.294556,-0.524638,-0.093180,0.077359,0.035804,0.241540,-0.309707,-0.122504,70.16,0

In [97]:
new_df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [98]:
new_df['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [99]:
new_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,93881.932927,-0.062153,-0.061179,0.090896,-0.008201,-0.083301,-0.030166,-0.041659,0.048504,0.017650,...,-0.033069,-0.002530,0.038295,-0.032350,0.01563,0.002376,0.009630,-0.023103,-0.024899,88.072134
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.10513,0.041449,0.051648,0.170575,0.075667,122.211321

### Splitting the data into Features and Target

In [100]:
X = new_df.drop(columns='Class', axis = 1)
Y = new_df['Class']

In [101]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
37059    38790.0 -0.327923  0.209546  1.200571 -1.127178 -0.099165 -0.284337
116424   74270.0 -1.142794  1.641385  0.865726  0.309667 -0.812529 -0.852074
62335    50233.0  1.135303 -0.024541  0.209504  0.479848 -0.298684 -0.685790
252637  155900.0 -0.531704  0.680875  0.597119 -1.028759  0.827708 -1.201487
180064  124360.0 -0.693474  0.643828  0.326878 -0.905386  1.281424 -0.016567
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
37059   0.523055  0.068633  0.108356  ...  0.012297  0.125672  0.227305
116424 -0.884873 -2.243079 -0.787290  ...  0.392414 -1.408377 -0.281292
62335   0.186939 -0.226366  0.012765  ...  0.132627 -0.237147 -0.855756
252637  1.171974 -0.241301 -0.185141  ... -0.161355  0.356074  0.982666
180064  1.581390 -0.503492 -0.189510  ... -0.083685 -0.294556 -0.524638
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
37059   0.124639 -0.233042 -0.470058  0.851426 -0.042892  0.028083   72.44
116424  0.340870  0.814892 -0.381256  0.011395 -0.161385  0.005226    1.98
62335  -0.001254 -0.096710  0.245629  0.220479 -0.050839  0.028222   87.28
252637 -0.369173 -0.060918  0.293462 -0.204899  0.091335  0.136623   19.95
180064 -0.093180  0.077359  0.035804  0.241540 -0.309707 -0.122504   70.16
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [102]:
print(Y)

37059     0
116424    0
62335     0
252637    0
180064    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

### Split the data into Training Data and Testing Data

In [109]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

print(X.shape, X_train.shape, X_test.shape)

## Model Treining
Using Logistic Regression

In [110]:
model = LogisticRegression()

In [111]:
# training the logistic Regression Model with Training Data
model.fit(X_train, Y_train)

C:\Users\osumb\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation based on the accuracy score

In [112]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [113]:
print('Accuracy on Training data: ', training_data_accuracy)

Accuracy on Training data:  0.9377382465057179

In [114]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [115]:
print('Accuracy score on Test data: ', test_data_accuracy)

Accuracy score on Test data:  0.9441624365482234